### ISSUE TITLE
상품 리스트 사진 읽어오기

### ISSUE THREAD

**Issue by SuranS2** [SuranS2/DBMarket#22]
- [x] 상품 이미지 경로 확인
- [x] 상품 이미지 저장 확인

**Comment by SuranS2** [comment]
changed due date to August 26, 2024

**Comment by SuranS2** [comment]
java.lang.NumberFormatException: For input string: "23413143312542"
(이미지 파일 body정보가 초과해서 침투한 것이라 추정됨)

**Comment by SuranS2** [comment]
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "NAME"; SQL statement:
update item set category=?,created_at=?,description=?,image_path=?,name=?,price=?,updated_at=?,user_id=? where item_id=? [23502-224]

**Comment by SuranS2** [comment]
t com.example.team1.Prometheus.controller.ItemDetailViewController.updateItem(ItemDetailViewController.java:38) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]

**Comment by SuranS2** [comment]
![image](https://my-gitlab-bucket.s3.amazonaws.com/850542890/de9074a61eddbf365a25b5d8c4c6f9a13d5dc56e86fcd21708f4eba1cf8e45b7/image.png)

front imagepath => imagePath

**Comment by SuranS2** [comment]
![image](https://my-gitlab-bucket.s3.amazonaws.com/850542890/c8800b329985b8bef7e5b2ca7fd074bd568f95fafc9c366073a000e2ee4a2d14/image.png)

**Comment by SuranS2** [comment]
![image](https://my-gitlab-bucket.s3.amazonaws.com/850542890/021b762f8d0ea1dca8de6e221120b21d14ffb9da5c890e32cd659d3ab57023bf/image.png)

현재 image 404notfound 문제가 나오지만
imageload를 다시 하면 문제가 없음

**Comment by SuranS2** [comment]
marked the task **상품 이미지 경로 확인** as completed

**Comment by SuranS2** [comment]
marked the task **상품 이미지 저장 확인** as completed

**Comment by SuranS2** [comment]
mentioned in commit 67a456c9207ca2b113cdfc47f5b0ce173d1a83fc
